// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ00MPp3yxP7TRagVhI2sFlVt5P4xhyLM',
    appId: '1:567396472986:android:e506e56a16c62d7a976723',
    messagingSenderId: '567396472986',
    projectId: 'paradox2k24-9d3a9',
    storageBucket: 'paradox2k24-9d3a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcms1lzCjTjzFD_t8JQeXXC5VAfQBrFS8',
    appId: '1:567396472986:ios:d59fe4bcdd30cad9976723',
    messagingSenderId: '567396472986',
    projectId: 'paradox2k24-9d3a9',
    storageBucket: 'paradox2k24-9d3a9.appspot.com',
    androidClientId: '567396472986-j8so8gidvluehqn5fk7tm0g28skp1a6b.apps.googleusercontent.com',
    iosClientId: '567396472986-r2khs8mpfrrvovh07ni90b9344f4j816.apps.googleusercontent.com',
    iosBundleId: 'com.example.paradox2024',
  );
}
